<a href="https://colab.research.google.com/github/SamuGasto/Climatic-Backend/blob/main/Ayudantia_M%C3%A9todos_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ayudantia 1 Métodos Numéricos(EJEMPLOS)

**Profesores: Scarlett Stegmann y Manuel Suil**

**Ayudantes: Mariel Arias y Valentin Valdenegro**

**APLICACIÓN DE NUMPY**


In [ ]:
import numpy as np
  #Cargamos las bibliotecas que utilizaremos en el codigo
  #En este caso, importamos NumPy para calculos y Matplotlib para gráficos
import matplotlib.pyplot as plt




**1.   CONSTANTES Y SUS "ACTUALIZACIONES"**







In [ ]:
#Ejemplo 1
# Constante de IVA inicial
IVA = 0.12
precio_base = 14890 #este precio puede variar según lo que se quieraa calcular

# Calculamos precio con IVA
precio_total = precio_base * (1 + IVA)
print("Precio con IVA inicial:", precio_total)

# Cambiamos el IVA a 19%
IVA = 0.19
precio_total = precio_base * (1 + IVA)
print("Precio con IVA actualizado:", precio_total)


Precio con IVA inicial: 16676.800000000003
Precio con IVA actualizado: 17719.1


In [ ]:
#Ejemplo 2
# Límite de velocidad inicial (km/h)
LIMITE_VELOCIDAD = 80

auto = 95
if auto > LIMITE_VELOCIDAD:
    print("Multa por exceder la velocidad límite")
else:
    print("Velocidad dentro del límite permitido")

# Se actualiza el límite (por cambios en la ley)
LIMITE_VELOCIDAD = 100

if auto > LIMITE_VELOCIDAD:
    print("Multa por exceder la velocidad límite")
else:
    print("Conducción dentro del límite permitido")


Multa por exceder la velocidad límite
Conducción dentro del límite permitido




**2.   LISTAS**


In [ ]:
#Ejemplo 1
#crear un lista
mascotas = ["gato", "perro", "pajaro", "pez"]
print(mascotas)

#Acceder a elementos de la lista
print(mascotas[0])
print(mascotas[3])#cabe recordar que en las listas el primer elemento es 0

#modificar elementos de la lista
mascotas[3] = "hamster"
print(mascotas)

#añadir elementos a la lista
mascotas.append("tortuga")
print(mascotas)

#eliminar elementos de la lista
mascotas.remove("gato")
print(mascotas)

#recorrer una lista
for mascota in mascotas:
    print(mascota)

['gato', 'perro', 'pajaro', 'pez']
gato
pez
['gato', 'perro', 'pajaro', 'hamster']
['gato', 'perro', 'pajaro', 'hamster', 'tortuga']
['perro', 'pajaro', 'hamster', 'tortuga']
perro
pajaro
hamster
tortuga


3. **FUNCIONES**

In [ ]:
#Ejemplo 1
# Función que recibe varios parámetros
def sumar(a, b):
    return a + b

# Llamamos a la función y almacenamos el resultado
resultado = sumar(10, 5)
print(resultado)


In [ ]:
#Ejemplo 2
# Definimos una función que recibe parámetros
def saludo(nombre):
    print(f"¡Hola, {nombre}! Bienvenido a la ayudantía de metodos")

# Llamamos a la función pasando un argumento
saludo("Carlos")


¡Hola, Carlos! Bienvenido a la ayudantía de metodos


4. **IF, ELIF Y ELSE**

In [ ]:
if condición:
    # código si la condición es True
elif otra_condición:
    # código si la anterior fue False y esta es True
else:
    # código si ninguna condición anterior es True

In [ ]:
#Ejemplo 1
# Verificamos el rango de edad de una persona
edad = 25

if edad < 18:
    print("Eres menor de edad.")
elif edad >= 18 and edad <= 30:
    print("Eres joven adulto.")
elif edad > 30 and edad <= 60:
    print("Eres adulto.")
else:
    print("Eres adulto mayor.")


In [ ]:
#Ejemplo 2
# Verificamos si un número es positivo, negativo o par/impar
numero = -4

if numero > 0:
    if numero % 2 == 0:
        print("El número es positivo y par.")
    else:
        print("El número es positivo e impar.")
elif numero < 0:
    if numero % 2 == 0:
        print("El número es negativo y par.")
    else:
        print("El número es negativo e impar.")
else:
    print("El número es cero.")


5.**RECURRENCIAS**

In [ ]:
#Ejemplo 1
# Lista de números
numeros = [1, 2, 3, 4, 5]

# Recorrer la lista e imprimir cada número
for numero in numeros:
    print(numero)


In [ ]:
#Ejemplo 2
# Calcular la suma de los números ingresados hasta que el usuario ingrese un número negativo
suma = 0
numero = int(input("Ingresa un número (negativo para terminar): "))

while numero >= 0:
    suma += numero
    numero = int(input("Ingresa un número (negativo para terminar): "))

print("La suma total es:", suma)


Ingresa un número (negativo para terminar): 1
Ingresa un número (negativo para terminar): 2
Ingresa un número (negativo para terminar): 3
Ingresa un número (negativo para terminar): 4
Ingresa un número (negativo para terminar): -3
La suma total es: 10


6. **Ejemplo de aplicacion numpy**

In [ ]:
# Paso 1: Crear una matriz de tamaño 4x4 con números aleatorios entre 1 y 100
matriz = np.random.randint(1, 101, (4, 4))
print("Matriz original:")
print(matriz)

# Paso 2: Sumar todos los elementos de la matriz
suma_matriz = np.sum(matriz)
print(f"\nLa suma de todos los elementos de la matriz es: {suma_matriz}")

# Paso 3: Verificar si la suma es par o impar
if suma_matriz % 2 == 0:
    print("La suma es par.")

    # Paso 4: Crear una nueva matriz con los cuadrados de los números de la matriz original
    cuadrados = np.array([[x**2 for x in fila] for fila in matriz])
    print("\nMatriz con los cuadrados de los elementos:")
    print(cuadrados)

else:
    print("La suma es impar.")

    # Paso 5: Calcular el promedio de los elementos de la matriz
    promedio = np.mean(matriz)
    print(f"\nEl promedio de los elementos de la matriz es: {promedio:.2f}")


Matriz original:
[[100  51  47  72]
 [  6  77  45  28]
 [ 86  49  76  76]
 [ 30   7  73   7]]

La suma de todos los elementos de la matriz es: 830
La suma es par.

Matriz con los cuadrados de los elementos:
[[10000  2601  2209  5184]
 [   36  5929  2025   784]
 [ 7396  2401  5776  5776]
 [  900    49  5329    49]]
